### ISSUE TITLE
Nil point dereference before changeProfilePic

### ISSUE THREAD

**Issue by jast-r** [Davincible/goinsta#24]
Hello, thx you for this repo! I'm trying to change my profile photo in my account, but I get nothing. I tried downloading a local file and repeating the code from the example, but I got the same result
This is my stack trace:

```
goroutine 1 [running]:
bytes.(*Buffer).Bytes(...)
        C:/Program Files/Go/src/bytes/buffer.go:54
github.com/Davincible/goinsta.(*UploadOptions).uploadPhoto(0xc0001abd00)
        C:/Users/Roman/go/pkg/mod/github.com/!davincible/goinsta@v0.0.0-20220219213948-e82ade6f84fc/uploads.go:239 +0x12f
github.com/Davincible/goinsta.(*Account).ChangeProfilePic(0xc00013c2c0, {0x1155a20, 0xc0004a0d80})
        C:/Users/Roman/go/pkg/mod/github.com/!davincible/goinsta@v0.0.0-20220219213948-e82ade6f84fc/account.go:187 +0x8d
main.main()
        C:/Users/Roman/Documents/Projects/goinsta_acci/cmd/insta_parser/main.go:46 +0x2ea
exit status 2

```

**Comment by Davincible** [comment]
Ah that was a bug! Thanks for reporting. Should be fixed now :)
