### ISSUE TITLE
Can't login with VPN, Instagram always asking security code and freeze on that step

### ISSUE THREAD

**Issue by turbo-cunnos** [Davincible/goinsta#27]
Hi. Thank you for your work. 
I have a strange problem with login process. I can't understand what i am do wrong.
Instagram always asking me a security code, that I entered from my email but after entering code the flow doesn't go forward.

I use simple code from example.
That log in the terminal I received:
```
Request Status Code 400: fail, challenge_required
Encountered a captcha challenge, goinsta will attempt to open the challenge in a headless chromium browser, and take a screenshot. Please report the details in a github issue.
Found button on challenge page: Send Security Code

Saved a screenshot of the challenge 'https://i.instagram.com/challenge/AXGMLQzEvEzsQTp_9KfvgRfFYc0q-xeroe3XNhcXID41f1tksB66iHo0fDyXQStAfuTk7qc/svwMx6SczQ2UhfXb/' to challenge-screenshot-1654070235.png, please report it in a github issue so the challenge can be solved automatiaclly.

panic: Failed to process challenge automatically with: Failed to solve challenge automatically

goroutine 1 [running]:
main.createAndSaveSession()
	/home/artgits/Documents/code/github/imago_venditator/controller.go:51 +0x12f
main.login()
	/home/artgits/Documents/code/github/imago_venditator/controller.go:26 +0x25
main.main()
	/home/artgits/Documents/code/github/imago_venditator/main.go:14 +0x25
```

**Comment by Davincible** [comment]
I will have a look at it

**Comment by justewg** [comment]
Hello. Is there are any solutions for problem above ? Problem is still actual
