### ISSUE TITLE
Failed to OpenApp after login

### ISSUE THREAD

**Issue by obalunenko** [Davincible/goinsta#45]
Hi @Davincible !
I faced with issues after update to 3.1.5 and 3.1.6 from v3.1.3 when OpenApp called after login.

Panic when trying to OpenApp after login on two accounts

```
Sending log in request..▀

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1011d3490]

goroutine 121 [running]:
github.com/Davincible/goinsta/v3.(*Discover).setValues(0x14000b94000?)
	github.com/Davincible/goinsta/v3@v3.1.6/explore.go:152 +0xc0
github.com/Davincible/goinsta/v3.(*Discover).Next(0x140000a8000)
	github.com/Davincible/goinsta/v3@v3.1.6/explore.go:119 +0x488
github.com/Davincible/goinsta/v3.(*Instagram).OpenApp.func8(0x0?)
	github.com/Davincible/goinsta/v3@v3.1.6/goinsta.go:677 +0x68
created by github.com/Davincible/goinsta/v3.(*Instagram).OpenApp
	github.com/Davincible/goinsta/v3@v3.1.6/goinsta.go:674 +0x6e4
```

And errors in logs for third account:

```
Sending log in request..▄
Non fatal error while fetching account family: Request Status Code 400: fail, consent_required
Sending log in request..▌
Non fatal error while fetching blocked media Request Status Code 400: fail, consent_required
Non fatal error while fetching config Request Status Code 400: fail, consent_required
Non fatal error while fetching notify badge Request Status Code 400: fail, consent_required
Non fatal error while fetching cool downs Request Status Code 400: fail, consent_required
Non fatal error while fetching bootstrap user scores Request Status Code 400: fail, consent_required
Non fatal error while fetching ndx steps: Request Status Code 400: fail, consent_required
Non fatal error while calling store client push permissions Request Status Code 400: fail, consent_required
Non fatal error while sending ad id Request Status Code 400: fail, consent_required
Non fatal error while fetching explore page Request Status Code 400: fail, consent_required
Sending log in request..▄
Non fatal error while fetching banyan Request Status Code 400: fail, consent_required
```

Environment:
github.com/Davincible/goinsta/v3@v3.1.6

go version
go version go1.19.5 darwin/arm64

**Comment by Davincible** [comment]
Hm I see, thanks for reporting, I'll have a look

**Comment by Davincible** [comment]
Should be fixed in `v3.1.7`. As for the consent_required, I've never seen that before, requires a bit more digging.

**Comment by obalunenko** [comment]
Thanks for quick response and for your fix.
